language: android
sudo: false
addons:
  apt:
    packages:
     - libgd2-xpm
     - ia32-libs
     - ia32-libs-multiarch
     - p7zip-full
before_install:
  - wget --timeout=120 http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86.bin -O ndk.bin
  - md5sum ndk.bin | grep c3edd3273029da1cbd2f62c48249e978
  - 7z x ndk.bin > /dev/null
  - export ANDROID_NDK=$(pwd)/android-ndk-r10e
  - printf "ndk.dir=$ANDROID_NDK" > local.properties
  - chmod +x gradlew
android:
  components:
    - build-tools-21.1.2
    - android-19
